shared:
  my_ci: &common_checks
    - check-success=ansible-lint / ansible-lint
    - check-success=Lint Code Base

queue_rules:
  - name: default
    conditions: *common_checks

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=queue-pr
      - and: *common_checks
    actions:
      queue:
        name: default
        method: squash
