shared:
  my_ci: &common_checks
    - and:
      - check-success=ansible-lint / ansible-lint
      - check-success=Lint Code Base
    - label~=^autorelease


queue_rules:
  - name: default
    conditions:
      - or: *common_checks


pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label=queue-pr
      - or: *common_checks
    actions:
      queue:
        name: default
        method: squash
