- hosts: localhost
  become: true
  vars_files:
    - variables/dotfiles.yml

  pre_tasks:
    - name: Add apt-repositories
      apt_repository:
        repo: ppa:ultradvorka/ppa
        state: present
      changed_when: False
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/fonts.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
