- hosts: all
  become: no
  vars: 
    user_home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"

  tasks:
    - include: roles/base.yml
    - include: roles/git.yml
    - include: roles/starship.yml
    - include: roles/zsh.yml
