- name: Install and configure git
  tags: [personal, work]
  block:
    - name: Install git
      ansible.builtin.apt:
        name: git
      become: true

    - name: Set email in git config
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"

    - name: Set username in git config
      community.general.git_config:
        name: user.name
        scope: global
        value: "Måns Östman"

    - name: Set default editor in git config
      community.general.git_config:
        name: core.editor
        scope: global
        value: vim
