- name: Install zsh
  ansible.builtin.apt:
    name:
      - zsh
  become: yes

- name: change user shell to zsh 
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: yes

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes

- name: Download zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Copy .zshrc to filesystem
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ user_home }}/.zshrc"
