---
- name: Check if cargo is installed
  ansible.builtin.command: cargo -v
  register: cargo_exists
  ignore_errors: true
  changed_when: false

- name: Download Installer
  when: cargo_exists.failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install rust/cargo
  when: cargo_exists.failed
  ansible.builtin.command: /tmp/sh.rustup.rs -y
