---
- name: Check if Teams is installed
  command: dpkg-query -W teams
  register: teams_check_deb
  failed_when: teams_check_deb.rc > 1
  changed_when: teams_check_deb.rc == 1

- name: Download deb file
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/{{ teams_deb }}"
    dest: "/tmp/{{ teams_deb }}"
    mode: "0644"
  when: teams_check_deb.rc == 1

- name: Install Teams
  apt: deb="/tmp/{{ teams_deb }}"
  become: true
  when: teams_check_deb.rc == 1
