---
- name: Check installed vscode extensions
  ansible.builtin.shell: |
    set -o pipefail
    code --list-extensions | tr '[:upper:]' '[:lower:]'
  args:
    executable: /bin/bash
  register: installed_extensions
  changed_when: false

- name: Install vscode extensions
  ansible.builtin.command: "code --install-extension {{ item }}"
  register: vscode_output
  changed_when: vscode_output.rc == 0
  loop: "{{ (vscode_extensions | difference(installed_extensions.stdout_lines)) }}"

- name: Copy user setting
  ansible.builtin.copy:
    src: settings.json
    dest: "{{ user_home }}/.config/Code/User/settings.json"
    mode: 0644
