- name: Make zsh default shell
  shell: chsh -s $(which zsh)

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  become: yes
  become_user: "{{ user }}"

- name: Download zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: yes
  become_user: "{{ user }}"
