---
name: Check job

on:
  push:
    branches-ignore:
      - main

jobs:
  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml
  super-linter:
    uses: ./.github/workflows/super-linter.yml

