---
name: Release job

on:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: CHANGELOG.md
  release-please:
    runs-on: ubuntu-latest
    needs:
      - super-linter
      - ansible-lint
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: cheesemans-ansible-provisioning
