---
name: release-please

on:
  workflow_call:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: cheesemans-ansible-provisioning
