---
name: Release job

on:
  push:
    branches:
      - main

jobs:
  lint-code-base:
    uses: ./.github/workflows/super-linter.yml
    with:
      validate-all-code-base: true
  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml
  release_please:
    needs: 
      - lint-code-base
      - ansible-lint
    uses: ./.github/workflows/release-please.yml

