---
name: Release job

on:
  push:
    branches:
      - main

jobs:
  ansible-lint:
    uses: ./.github/workflows/ansible-lint.yml
  super-linter:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: CHANGELOG.md

  release_please:
    needs:
      - lint-code-base
      - ansible-lint
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: cheesemans-ansible-provisioning

