---
name: Release job

on:
  push:
    branches:
      - main

jobs:
  lint_code_base:
    uses: ./.github/workflows/super-linter.yml
    with:
      validate-all-code-base: true
  release_please:
    uses: ./.github/workflows/release-please.yml

